use EmployeeManagementDb
CREATE TABLE UsersDb (UserId INT IDENTITY(1,1) PRIMARY KEY, UserName NVARCHAR(110) NOT NULL UNIQUE, Email NVARCHAR(110) NOT NULL UNIQUE,
PasswordHash NVARCHAR(255),Role NVARCHAR(20) NOT NULL DEFAULT 'User' ,CreatedAt DATETIME NOT NULL DEFAULT GETDATE())

CREATE TABLE EmployeeDb (EmployeeId INT IDENTITY(1,1) PRIMARY KEY ,EmployeeName NVARCHAR(110) NOT NULL ,Email NVARCHAR(110) NOT NULL ,Address
 NVARCHAR(255) NOT NULL ,Department NVARCHAR(110) NOT NULL, Position NVARCHAR(110),Salary  DECIMAL(18,2) NOT NULL ,CreatedAt DATETIME DEFAULT GETDATE()
 )